const categories = [
    "Science Fiction",
    "Fantasy",
    "Horror",
    "Crime",
    "Historical Fiction",
    "Dystopian",
    "Action",
    "Adventure",
    "Mystery",
    "Thriller",
    "Suspense",
    "Romance",
    "Young Adult",
    "Graphic Novel",
    "Short Story",
    "Children",
    "Autobiography",
    "Biography",
    "Food & Drink",
    "Art & Photography",
    "Self-help",
    "Travel",
    "True Crime",
    "Humour",
    "Education",
    "Guide",
    "Religion",
    "Politics",
    "Parenting & Family",
    "Social Studies",
    "Philosophy",
    "Science & Tech",
    "History"
];

export default categories;

export const fiction = [
    "Science Fiction",
    "Fantasy",
    "Horror",
    "Crime",
    "Historical Fiction",
    "Dystopian",
    "Action",
    "Adventure",
    "Mystery",
    "Thriller",
    "Suspense",
    "Romance",
    "Young Adult",
    "Graphic Novel",
    "Short Story",
    "Children"
];

export const nonFiction = [
    "Autobiography",
    "Biography",
    "Food & Drink",
    "Art & Photography",
    "Self-help",
    "Travel",
    "True Crime",
    "Humour",
    "Education",
    "Guide",
    "Religion",
    "Politics",
    "Parenting & Family",
    "Social Studies",
    "Philosophy",
    "Science & Tech",
    "History"
];